
GRANT USAGE ON SCHEMA DEV_DB.ANIME_STACKEXCHANGE_SOURCE TO ROLE CI_CD_ROLE_DEV;
GRANT USAGE ON SCHEMA DEV_DB.BEER_STACKEXCHANGE_SOURCE TO ROLE CI_CD_ROLE_DEV;

-- For internal stages, READ must be granted before WRITE
GRANT READ ON STAGE DEV_DB.ANIME_STACKEXCHANGE_SOURCE.RAW_STAGE TO ROLE CI_CD_ROLE_DEV;
GRANT READ ON STAGE DEV_DB.BEER_STACKEXCHANGE_SOURCE.RAW_STAGE TO ROLE CI_CD_ROLE_DEV;

GRANT WRITE ON STAGE DEV_DB.ANIME_STACKEXCHANGE_SOURCE.RAW_STAGE TO ROLE CI_CD_ROLE_DEV;
GRANT WRITE ON STAGE DEV_DB.BEER_STACKEXCHANGE_SOURCE.RAW_STAGE TO ROLE CI_CD_ROLE_DEV;

GRANT CREATE TABLE ON SCHEMA DEV_DB.ANIME_STACKEXCHANGE_SOURCE TO ROLE CI_CD_ROLE_DEV;
GRANT CREATE TABLE ON SCHEMA DEV_DB.BEER_STACKEXCHANGE_SOURCE TO ROLE CI_CD_ROLE_DEV;

GRANT CREATE PROCEDURE ON SCHEMA DEV_DB.ANIME_STACKEXCHANGE_SOURCE TO ROLE CI_CD_ROLE_DEV;
GRANT CREATE PROCEDURE ON SCHEMA DEV_DB.BEER_STACKEXCHANGE_SOURCE TO ROLE CI_CD_ROLE_DEV;

GRANT READ ON FUTURE STAGES IN SCHEMA DEV_DB.ANIME_STACKEXCHANGE_SOURCE TO ROLE CI_CD_ROLE_DEV;
GRANT READ ON FUTURE STAGES IN SCHEMA DEV_DB.BEER_STACKEXCHANGE_SOURCE TO ROLE CI_CD_ROLE_DEV;

GRANT WRITE ON FUTURE STAGES IN SCHEMA DEV_DB.ANIME_STACKEXCHANGE_SOURCE TO ROLE CI_CD_ROLE_DEV;
GRANT WRITE ON FUTURE STAGES IN SCHEMA DEV_DB.BEER_STACKEXCHANGE_SOURCE TO ROLE CI_CD_ROLE_DEV;

