CREATE OR REPLACE TABLE BEER_STACKEXCHANGE_SOURCE.BADGES_RAW (
    RAW_XML VARIANT,
    SOURCE_FILE STRING,
    LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
CREATE OR REPLACE TABLE BEER_STACKEXCHANGE_SOURCE.COMMENTS_RAW (
    RAW_XML VARIANT,
    SOURCE_FILE STRING,
    LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
CREATE OR REPLACE TABLE BEER_STACKEXCHANGE_SOURCE.POSTHISTORY_RAW (
    RAW_XML VARIANT,
    SOURCE_FILE STRING,
    LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
CREATE OR REPLACE TABLE BEER_STACKEXCHANGE_SOURCE.POSTLINKS_RAW (
    RAW_XML VARIANT,
    SOURCE_FILE STRING,
    LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
CREATE OR REPLACE TABLE BEER_STACKEXCHANGE_SOURCE.POSTS_RAW (
    RAW_XML VARIANT,
    SOURCE_FILE STRING,
    LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
CREATE OR REPLACE TABLE BEER_STACKEXCHANGE_SOURCE.TAGS_RAW (
    RAW_XML VARIANT,
    SOURCE_FILE STRING,
    LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
CREATE OR REPLACE TABLE BEER_STACKEXCHANGE_SOURCE.USERS_RAW (
    RAW_XML VARIANT,
    SOURCE_FILE STRING,
    LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
CREATE OR REPLACE TABLE BEER_STACKEXCHANGE_SOURCE.VOTES_RAW (
    RAW_XML VARIANT,
    SOURCE_FILE STRING,
    LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);



