CREATE OR REPLACE FILE FORMAT ANIME_STACKEXCHANGE_SOURCE.XML_STACKEXCHANGE_FORMAT
    TYPE = 'XML'
    COMPRESSION = 'AUTO';
    
CREATE OR REPLACE FILE FORMAT BEER_STACKEXCHANGE_SOURCE.XML_STACKEXCHANGE_FORMAT
    TYPE = 'XML'
    COMPRESSION = 'AUTO';