USE ROLE DEVELOPER;

GRANT USAGE ON SCHEMA DEV_DB.ANIME_STACKEXCHANGE_SOURCE TO ROLE CI_CD_ROLE_DEV;
GRANT USAGE ON SCHEMA DEV_DB.BEER_STACKEXCHANGE_SOURCE TO ROLE CI_CD_ROLE_DEV;

GRANT WRITE ON STAGE DEV_DB.ANIME_STACKEXCHANGE_SOURCE.RAW_STAGE TO ROLE CI_CD_ROLE_DEV;
GRANT WRITE ON STAGE DEV_DB.BEER_STACKEXCHANGE_SOURCE.RAW_STAGE TO ROLE CI_CD_ROLE_DEV;

GRANT WRITE ON FUTURE STAGES IN SCHEMA DEV_DB.ANIME_STACKEXCHANGE_SOURCE TO ROLE CI_CD_ROLE_DEV;
GRANT WRITE ON FUTURE STAGES IN SCHEMA DEV_DB.BEER_STACKEXCHANGE_SOURCE TO ROLE CI_CD_ROLE_DEV;

GRANT USAGE ON SCHEMA QA_DB.ANIME_STACKEXCHANGE_SOURCE TO ROLE CI_CD_ROLE_UAT;
GRANT USAGE ON SCHEMA QA_DB.BEER_STACKEXCHANGE_SOURCE TO ROLE CI_CD_ROLE_UAT;

GRANT WRITE ON STAGE QA_DB.ANIME_STACKEXCHANGE_SOURCE.RAW_STAGE TO ROLE CI_CD_ROLE_UAT;
GRANT WRITE ON STAGE QA_DB.BEER_STACKEXCHANGE_SOURCE.RAW_STAGE TO ROLE CI_CD_ROLE_UAT;

GRANT WRITE ON FUTURE STAGES IN SCHEMA QA_DB.ANIME_STACKEXCHANGE_SOURCE TO ROLE CI_CD_ROLE_UAT;
GRANT WRITE ON FUTURE STAGES IN SCHEMA QA_DB.BEER_STACKEXCHANGE_SOURCE TO ROLE CI_CD_ROLE_UAT;

GRANT USAGE ON SCHEMA PROD_DB.ANIME_STACKEXCHANGE_SOURCE TO ROLE CI_CD_ROLE_PROD;
GRANT USAGE ON SCHEMA PROD_DB.BEER_STACKEXCHANGE_SOURCE TO ROLE CI_CD_ROLE_PROD;

GRANT WRITE ON STAGE PROD_DB.ANIME_STACKEXCHANGE_SOURCE.RAW_STAGE TO ROLE CI_CD_ROLE_PROD;
GRANT WRITE ON STAGE PROD_DB.BEER_STACKEXCHANGE_SOURCE.RAW_STAGE TO ROLE CI_CD_ROLE_PROD;

GRANT WRITE ON FUTURE STAGES IN SCHEMA PROD_DB.ANIME_STACKEXCHANGE_SOURCE TO ROLE CI_CD_ROLE_PROD;
GRANT WRITE ON FUTURE STAGES IN SCHEMA PROD_DB.BEER_STACKEXCHANGE_SOURCE TO ROLE CI_CD_ROLE_PROD;