
CREATE OR REPLACE STAGE ANIME_STACKEXCHANGE_SOURCE.RAW_STAGE
  FILE_FORMAT = ANIME_STACKEXCHANGE_SOURCE.XML_STACKEXCHANGE_FORMAT;

CREATE OR REPLACE STAGE BEER_STACKEXCHANGE_SOURCE.RAW_STAGE
  FILE_FORMAT = BEER_STACKEXCHANGE_SOURCE.XML_STACKEXCHANGE_FORMAT;
