CREATE OR REPLACE TABLE ANIME_STACKEXCHANGE_SOURCE.PIPELINE_LOG (
    LOG_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    TABLE_NAME STRING,
    PIPELINE_STEP STRING,  -- 'LOAD_TO_RAW' or 'DEDUPLICATE_TO_STAGED'
    STATUS STRING,  -- 'SUCCESS' or 'ERROR'
    MESSAGE STRING,
    ROWS_PROCESSED NUMBER,
    EXECUTION_TIME_SECONDS NUMBER,
    CREATED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE BEER_STACKEXCHANGE_SOURCE.PIPELINE_LOG (
    LOG_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    TABLE_NAME STRING,
    PIPELINE_STEP STRING,  -- 'LOAD_TO_RAW' or 'DEDUPLICATE_TO_STAGED'
    STATUS STRING,  -- 'SUCCESS' or 'ERROR'
    MESSAGE STRING,
    ROWS_PROCESSED NUMBER,
    EXECUTION_TIME_SECONDS NUMBER,
    CREATED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
