-- Create Staged/Deduplicated Tables for Anime StackExchange
CREATE OR REPLACE TABLE ANIME_STACKEXCHANGE_SOURCE.POSTS_STAGED (
    ID NUMBER PRIMARY KEY,
    POST_TYPE_ID NUMBER,
    ACCEPTED_ANSWER_ID NUMBER,
    PARENT_ID NUMBER,
    CREATION_DATE TIMESTAMP_NTZ,
    SCORE NUMBER,
    VIEW_COUNT NUMBER,
    BODY STRING,
    OWNER_USER_ID NUMBER,
    OWNER_DISPLAY_NAME STRING,
    LAST_EDITOR_USER_ID NUMBER,
    LAST_EDITOR_DISPLAY_NAME STRING,
    LAST_EDIT_DATE TIMESTAMP_NTZ,
    LAST_ACTIVITY_DATE TIMESTAMP_NTZ,
    TITLE STRING,
    TAGS STRING,
    ANSWER_COUNT NUMBER,
    COMMENT_COUNT NUMBER,
    FAVORITE_COUNT NUMBER,
    CLOSED_DATE TIMESTAMP_NTZ,
    COMMUNITY_OWNED_DATE TIMESTAMP_NTZ,
    CONTENT_LICENSE STRING,
    PROCESSED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Users Staged Table
CREATE OR REPLACE TABLE ANIME_STACKEXCHANGE_SOURCE.USERS_STAGED (
    ID NUMBER PRIMARY KEY,
    REPUTATION NUMBER,
    CREATION_DATE TIMESTAMP_NTZ,
    DISPLAY_NAME STRING,
    LAST_ACCESS_DATE TIMESTAMP_NTZ,
    WEBSITE_URL STRING,
    LOCATION STRING,
    ABOUT_ME STRING,
    VIEWS NUMBER,
    UPVOTES NUMBER,
    DOWNVOTES NUMBER,
    PROFILE_IMAGE_URL STRING,
    ACCOUNT_ID NUMBER,
    PROCESSED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Comments Staged Table
CREATE OR REPLACE TABLE ANIME_STACKEXCHANGE_SOURCE.COMMENTS_STAGED (
    ID NUMBER PRIMARY KEY,
    POST_ID NUMBER,
    SCORE NUMBER,
    TEXT STRING,
    CREATION_DATE TIMESTAMP_NTZ,
    USER_DISPLAY_NAME STRING,
    USER_ID NUMBER,
    CONTENT_LICENSE STRING,
    PROCESSED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Badges Staged Table
CREATE OR REPLACE TABLE ANIME_STACKEXCHANGE_SOURCE.BADGES_STAGED (
    ID NUMBER PRIMARY KEY,
    USER_ID NUMBER,
    NAME STRING,
    DATE TIMESTAMP_NTZ,
    CLASS NUMBER,
    TAG_BASED BOOLEAN,
    PROCESSED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Tags Staged Table
CREATE OR REPLACE TABLE ANIME_STACKEXCHANGE_SOURCE.TAGS_STAGED (
    ID NUMBER PRIMARY KEY,
    TAG_NAME STRING,
    COUNT NUMBER,
    EXCERPT_POST_ID NUMBER,
    WIKI_POST_ID NUMBER,
    PROCESSED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Votes Staged Table
CREATE OR REPLACE TABLE ANIME_STACKEXCHANGE_SOURCE.VOTES_STAGED (
    ID NUMBER PRIMARY KEY,
    POST_ID NUMBER,
    VOTE_TYPE_ID NUMBER,
    USER_ID NUMBER,
    CREATION_DATE TIMESTAMP_NTZ,
    BountyAmount NUMBER,
    PROCESSED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- PostHistory Staged Table
CREATE OR REPLACE TABLE ANIME_STACKEXCHANGE_SOURCE.POSTHISTORY_STAGED (
    ID NUMBER PRIMARY KEY,
    POST_HISTORY_TYPE_ID NUMBER,
    POST_ID NUMBER,
    REVISION_GUID STRING,
    CREATION_DATE TIMESTAMP_NTZ,
    USER_ID NUMBER,
    USER_DISPLAY_NAME STRING,
    COMMENT STRING,
    TEXT STRING,
    CONTENT_LICENSE STRING,
    PROCESSED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- PostLinks Staged Table
CREATE OR REPLACE TABLE ANIME_STACKEXCHANGE_SOURCE.POSTLINKS_STAGED (
    ID NUMBER PRIMARY KEY,
    CREATION_DATE TIMESTAMP_NTZ,
    POST_ID NUMBER,
    RELATED_POST_ID NUMBER,
    LINK_TYPE_ID NUMBER,
    PROCESSED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================
-- Create Staged/Deduplicated Tables for Beer StackExchange
-- ============================================

-- Posts Staged Table
CREATE OR REPLACE TABLE BEER_STACKEXCHANGE_SOURCE.POSTS_STAGED (
    ID NUMBER PRIMARY KEY,
    POST_TYPE_ID NUMBER,
    ACCEPTED_ANSWER_ID NUMBER,
    PARENT_ID NUMBER,
    CREATION_DATE TIMESTAMP_NTZ,
    SCORE NUMBER,
    VIEW_COUNT NUMBER,
    BODY STRING,
    OWNER_USER_ID NUMBER,
    OWNER_DISPLAY_NAME STRING,
    LAST_EDITOR_USER_ID NUMBER,
    LAST_EDITOR_DISPLAY_NAME STRING,
    LAST_EDIT_DATE TIMESTAMP_NTZ,
    LAST_ACTIVITY_DATE TIMESTAMP_NTZ,
    TITLE STRING,
    TAGS STRING,
    ANSWER_COUNT NUMBER,
    COMMENT_COUNT NUMBER,
    FAVORITE_COUNT NUMBER,
    CLOSED_DATE TIMESTAMP_NTZ,
    COMMUNITY_OWNED_DATE TIMESTAMP_NTZ,
    CONTENT_LICENSE STRING,
    PROCESSED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Users Staged Table
CREATE OR REPLACE TABLE BEER_STACKEXCHANGE_SOURCE.USERS_STAGED (
    ID NUMBER PRIMARY KEY,
    REPUTATION NUMBER,
    CREATION_DATE TIMESTAMP_NTZ,
    DISPLAY_NAME STRING,
    LAST_ACCESS_DATE TIMESTAMP_NTZ,
    WEBSITE_URL STRING,
    LOCATION STRING,
    ABOUT_ME STRING,
    VIEWS NUMBER,
    UPVOTES NUMBER,
    DOWNVOTES NUMBER,
    PROFILE_IMAGE_URL STRING,
    ACCOUNT_ID NUMBER,
    PROCESSED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Comments Staged Table
CREATE OR REPLACE TABLE BEER_STACKEXCHANGE_SOURCE.COMMENTS_STAGED (
    ID NUMBER PRIMARY KEY,
    POST_ID NUMBER,
    SCORE NUMBER,
    TEXT STRING,
    CREATION_DATE TIMESTAMP_NTZ,
    USER_DISPLAY_NAME STRING,
    USER_ID NUMBER,
    CONTENT_LICENSE STRING,
    PROCESSED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Badges Staged Table
CREATE OR REPLACE TABLE BEER_STACKEXCHANGE_SOURCE.BADGES_STAGED (
    ID NUMBER PRIMARY KEY,
    USER_ID NUMBER,
    NAME STRING,
    DATE TIMESTAMP_NTZ,
    CLASS NUMBER,
    TAG_BASED BOOLEAN,
    PROCESSED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Tags Staged Table
CREATE OR REPLACE TABLE BEER_STACKEXCHANGE_SOURCE.TAGS_STAGED (
    ID NUMBER PRIMARY KEY,
    TAG_NAME STRING,
    COUNT NUMBER,
    EXCERPT_POST_ID NUMBER,
    WIKI_POST_ID NUMBER,
    PROCESSED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Votes Staged Table
CREATE OR REPLACE TABLE BEER_STACKEXCHANGE_SOURCE.VOTES_STAGED (
    ID NUMBER PRIMARY KEY,
    POST_ID NUMBER,
    VOTE_TYPE_ID NUMBER,
    USER_ID NUMBER,
    CREATION_DATE TIMESTAMP_NTZ,
    BountyAmount NUMBER,
    PROCESSED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- PostHistory Staged Table
CREATE OR REPLACE TABLE BEER_STACKEXCHANGE_SOURCE.POSTHISTORY_STAGED (
    ID NUMBER PRIMARY KEY,
    POST_HISTORY_TYPE_ID NUMBER,
    POST_ID NUMBER,
    REVISION_GUID STRING,
    CREATION_DATE TIMESTAMP_NTZ,
    USER_ID NUMBER,
    USER_DISPLAY_NAME STRING,
    COMMENT STRING,
    TEXT STRING,
    CONTENT_LICENSE STRING,
    PROCESSED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- PostLinks Staged Table
CREATE OR REPLACE TABLE BEER_STACKEXCHANGE_SOURCE.POSTLINKS_STAGED (
    ID NUMBER PRIMARY KEY,
    CREATION_DATE TIMESTAMP_NTZ,
    POST_ID NUMBER,
    RELATED_POST_ID NUMBER,
    LINK_TYPE_ID NUMBER,
    PROCESSED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
